import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Lock, Search, Settings, Sparkles } from "lucide-react";
import { GlowingEffect } from "./glowing-effect";
import "./whychoose.css";
import { Heading } from "@components/heading";
export function GlowingEffectDemo() {
    return (_jsxs("section", { className: "flex flex-col gap-22 whychoose-section", children: [_jsx(Heading, { title: "Why Asrnova" }), _jsx("div", { children: _jsxs("ul", { className: "grid grid-cols-1 sm:h-[44rem] w-[75%] grid-rows-none !gap-10 md:grid-cols-12 md:grid-rows-3 lg:gap-4 xl:max-h-[34rem] xl:grid-rows-2", children: [_jsx(GridItem, { area: "md:[grid-area:1/1/2/7] xl:[grid-area:1/1/2/5]", icon: _jsx(Box, { className: "h-4 w-4 text-black dark:text-neutral-400" }), title: " Original Ideas Only", description: "We don\u2019t recycle old trends or templates. Every project is treated like a fresh canvas \u2014 unique, bold, and built from scratch with purpose." }), _jsx(GridItem, { area: "md:[grid-area:1/7/2/13] xl:[grid-area:2/1/3/5]", icon: _jsx(Settings, { className: "h-4 w-4 text-black dark:text-neutral-400" }), title: "No Boring Projects", description: "We avoid cookie-cutter sites that lack soul. If it\u2019s been done a thousand times, it\u2019s not for us. We\u2019re here for work that excites and inspires." }), _jsx(GridItem, { area: "md:[grid-area:2/1/3/7] xl:[grid-area:1/5/3/8]", icon: _jsx(Lock, { className: "h-4 w-4 text-black dark:text-neutral-400" }), title: "Future Driven Solution", description: "At asrnova, we don't chase what\u2019s already out there. We craft digital experiences with tomorrow in mind \u2014 innovative, scalable, and truly ahead of the curve." }), _jsx(GridItem, { area: "md:[grid-area:2/7/3/13] xl:[grid-area:1/8/2/13]", icon: _jsx(Sparkles, { className: "h-4 w-4 text-black dark:text-neutral-400" }), title: "Focused on What Matters", description: "Quality over quantity \u2014 always. We take on fewer projects so we can go deep, challenge the norm, and deliver work that stands out." }), _jsx(GridItem, { area: "md:[grid-area:3/1/4/13] xl:[grid-area:2/8/3/13]", icon: _jsx(Search, { className: "h-4 w-4 text-black dark:text-neutral-400" }), title: "Creative Growth Partners", description: "We\u2019re not just developers. We\u2019re collaborators, thinkers, and partners in your journey \u2014 helping you explore ideas you didn\u2019t know were possible." })] }) })] }));
}
const GridItem = ({ area, icon, title, description }) => {
    return (_jsx("li", { className: `min-h-[14rem] list-none ${area}`, children: _jsxs("div", { className: "relative h-full rounded-2xl border  md:rounded-3xl md:!p-3", children: [_jsx(GlowingEffect, { blur: 0, borderWidth: 3, spread: 80, glow: true, disabled: false, proximity: 64, inactiveZone: 0.01 }), _jsx("div", { className: "border-0.75 relative flex h-full flex-col justify-between gap-6 overflow-hidden rounded-xl !p-6 md:!p-6 dark:shadow-[0px_0px_27px_0px_#2D2D2D]", children: _jsxs("div", { className: "relative flex flex-1 flex-col justify-between gap-3", children: [_jsx("div", { className: "w-fit rounded-lg border border-gray-600 !p-2", children: icon }), _jsxs("div", { className: "space-y-3", children: [_jsx("h3", { className: "-tracking-4 azonix pt-0.5 font-sans text-xl/[1.375rem] font-semibold text-balance text-black md:text-2xl/[1.875rem] dark:text-white", children: title }), _jsx("h2", { className: "font-sans text-sm/[1.125rem] text-black md:text-base/[1.375rem] dark:text-neutral-400 [&_b]:md:font-semibold [&_strong]:md:font-semibold", children: description })] })] }) })] }) }));
};
