import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import './styles.css';
import SwingingRobot from './swingingRobot';
import ParallaxEffect from './textMoving';
import { ButtoninBookaCall } from '../../../../components/buttonForHero';
const Hero = ({ handleScrollToBook }) => {
    return (_jsxs("section", { className: "heroPageMainSection sm:h-dvh flex flex-col overflow-hidden w-full m-auto gap-10 !pb-10", children: [_jsx("div", { className: "contentInHeroPage flex flex-col gap-10 w-full h-full justify-center items-center ", children: _jsxs("div", { className: "flex flex-col sm:flex-row sm:w-[70%] justify-between items-center", children: [_jsxs(motion.div, { className: "textContent flex flex-col gap-6 sm:w-[70%] items-center sm:items-start", initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 1, ease: 'easeOut' }, children: [_jsxs(motion.h1, { className: "ethnocentric text-center sm:text-left text-2xl sm:text-4xl max-sm:text-[18px] font-bold bg-gradient-to-r from-[#00F5A0] to-[#00A3FF] bg-clip-text text-transparent leading-tight ", initial: { opacity: 0, x: -40 }, animate: { opacity: 1, x: 0 }, transition: { duration: 1, ease: 'easeOut', delay: 0.3 }, children: ["Websites Fade, ", _jsx("br", {}), " Stories Last Forever"] }), _jsxs(motion.p, { className: "orbitron text-xl text-[#000000] leading-relaxed w-[80%] max-sm:text-[14px] max-sm:text-center sm:w-full ", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 1, delay: 0.5 }, children: ["Your business is more than just a service \u2013 it\u2019s a story waiting to be told. At", ' ', _jsx("span", { className: "font-semibold text-[#00A3FF]", children: "Asrnova" }), ", we create digital experiences that make your brand impossible to ignore."] }), _jsx(ButtoninBookaCall, { text: "Get in touch", onClick: handleScrollToBook })] }), _jsx(motion.div, { initial: { opacity: 0, x: 40 }, animate: { opacity: 1, x: 0 }, transition: { duration: 1, delay: 0.6 }, children: _jsx(SwingingRobot, {}) })] }) }), _jsx("div", { className: "movingText w-[100%]", children: _jsx(ParallaxEffect, {}) })] }));
};
export default Hero;
