import './ballMoving.css'
const BallMoving = () => {
    return (
        <div className='ballMovingScene'>
            <div className="scene">
                <div className="grid">
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                    <i><i></i><i></i></i>
                </div>
                <div className="ball">
                    <i></i>
                </div>
            </div>
        </div>
    )
}

export default BallMoving